### PR TITLE
Fix crash on renaming a floating pane (#1323)

### PR DESCRIPTION
**Pull request by raphCode**

### CODE REVIEW

**Comment by raphCode** [comment]
Ideally we add some tests to avoid regressions, but to be honest, I hate writing tests and also the huge e2e test functions scared me away.
It looks like some sort of [Tcl expect](https://en.wikipedia.org/wiki/Expect) just for terminal UI that updates via ANSI sequences?

**Comment by imsnif** [comment]
> Ideally we add some tests to avoid regressions, but to be honest, I hate writing tests and also the huge e2e test functions scared me away. It looks like some sort of [Tcl expect](https://en.wikipedia.org/wiki/Expect) just for terminal UI that updates via ANSI sequences?

That would be great! The e2e tests are indeed a bit of a handful (as such tests tend to be), but for this maybe you can add an integration test? https://github.com/zellij-org/zellij/blob/main/zellij-server/src/tab/unit/tab_integration_tests.rs

Wdyt?

**Comment by raphCode** [comment]
Added some test
---

In case you are interested in my experiences:

It looked difficult at first, because I did not find a definiton of `assert_snapshot!`. The insta testing library make things actually much easier and also allows to view the rendered zellij UI. Nice!

**Review by imsnif — APPROVED** [review]
Breaking `Tab` into like... 17 different modules is totally on my list for the not too far future, I very much agree.

Otherwise about the tests - this is good feedback. Do you have suggestions about what we should change that would have made your experience easier?

This LGTM. Please feel free to merge, and don't forget to update the changelog.

**Comment by raphCode** [comment]
> Do you have suggestions about what we should change that would have made your experience easier?

Some high level dev docs or a guide on e.g. how to add a test would be super nice. But I totally understand if this maybe is too much to ask for, many projects do not have this and it can also be a maintenance burden since dev docs must be kept up-to-date on code changes.

In general, when doing something for the first time and having no idea on how to approach it, it costs me quite a bit willpower and motivaton to work my way into it. A guide lowers this barrier because it shows a potential path through the problem space and familiarizes me with any new tools involved.
In fact, https://insta.rs/docs/quickstart/ was enough to get to know insta and become comfortable with its workflow. From there, I worked my way backwards through the tests by reverse engineering them: seeing what each line did change in the snapshot.

**Pull request merged**
