### PR TITLE
Sending mouse events to the terminal

### LINKED ISSUE #579: No mouse support in neovim
**Basic information**

`zellij --version`: 0.13.0
`tput lines`: 68
`tput cols`: 256
`uname -av` or `ver`(Windows): Linux PO19258LX 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

List of programs you interact with:
`nvim --version`: neovim-0.5.0+ubuntu2+git202106170012-c78816eb6-d569569c9
`alacritty --version`: alacritty 0.8.0

**Further information**

When I edit a file with neovim in Zellij the mouse is not captured by neovim (visual selection etc). 

I don’t know if it should be reported in #448

### PR DESCRIPTION
**Pull request by dantepippi**
Sending terminals the ANSI/VT commands for mouse events
Closes #579

### CODE REVIEW

**Comment by imsnif** [comment]
Hey, @dantepippi - is this PR ready? I just noticed it's been marked as ready for review a while ago. I don't think I get notifications for that sort of thing. :)

**Comment by TheLostLambda** [comment]
Seems good overall to me, but causes some issues when in something like `nvim` and there is also a scrollback on the terminal. It still tries to scroll the scroll-buffer instead of just passing through the event. Perhaps we need to listen out for applications wanting to capture the mouse? If there is a signal for that?

**Comment by tlinford** [comment]
@TheLostLambda There are actually multiple signals related to mouse events: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking.
So for example the sequence we are using to enable mouse mode (via Termion) is: `"?1000h\x1b[?1002h\x1b[?1015h\x1b[?1006h"`

**Comment by imsnif** [comment]
Iirc this is not ready yet, so I guess that's why it's still not working :)

**Comment by tlinford** [comment]
Closing this as it was superseded by #1191.

**Pull request closed without merging**
