### PR TITLE
Updated names and dialoguer crates dependencies

### PR DESCRIPTION
**Pull request by Laiot**
I tried to build and run zellij with the updated dependencies and they seem to show no issues.
I need this in order to package zellij for Fedora.

### CODE REVIEW

**Comment by Laiot** [comment]
I don't understand why the build fails on the Nix OS. Any idea?

**Comment by a-kenji** [comment]
You bumped the dependencies solely in the `Cargo.toml` file, which is sufficient for libraries, but shouldn't be sufficient for applications.

https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

I expect it will work, if you run:
```
cargo update -p dialoguer -p names
```
And commit the `Cargo.lock` file.

**Comment by Laiot** [comment]
Sorry about that, I just forgot to commit the Cargo.lock
It should be updated since I ran a local build.

**Comment by a-kenji** [comment]
No worries!
It happens, luckily we have a CI that can catch these things.
I hope I can get time to look at the crates in more depth soon.

**Comment by a-kenji** [comment]
@Laiot,
Thank you!
Please do reach out in the future.

**Pull request merged**
