### PR TITLE
fix(feat): `disable_automatic_asset_installation`

### LINKED ISSUE #1130: PermissionDenied even when built with features=disable_automatic_asset_installation
`zellij --version`: zellij 0.25.0
`tput lines`: 72
`tput cols`: 271
`uname -av`: `Linux ALESSAND-F1E8 5.16.2-rt-rt19-x86_64 #5 SMP PREEMPT Tue Feb 15 19:20:22 CET 2022 x86_64 AMD Ryzen 5 3600 6-Core Processor AuthenticAMD GNU/Linux`

**Further information**
I've built zellij with `features=disable_automatic_asset_installation` and installed it in `/usr` but it will crash with
```
zellij options --simplified-ui true
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', src/install.rs:33:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

relevant part of `strace`

```
statx(AT_FDCWD, "/home/ale/.config/zellij", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0755, stx_size=22, ...}) = 0
openat(AT_FDCWD, "/home/ale/.config/zellij/layouts/default", O_RDONLY|O_CLOEXEC) = -1 ENOENT (File o directory non esistente)
openat(AT_FDCWD, "/home/ale/.config/zellij/layouts/default.yaml", O_RDONLY|O_CLOEXEC) = -1 ENOENT (File o directory non esistente)
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
getrandom("", 0, 0)                     = 0
getrandom("\xc8\x7e\xd8\x18\x8b\x2b\x3d\xa1\x11\x80\xe9\x26\xc7\x0e\x95\xc8\x2a\xfe\x98\x6b\xc7\xbc\x04\x1c\xab\xef\x83\xf0\x75\xe0\xfd\xeb"..., 2048, 0) = 2048
openat(AT_FDCWD, "/run/user/1000/zellij/0.25.0", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (File o directory non esistente)
statx(AT_FDCWD, "/home/ale/.local/share/zellij", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffc642d4300) = -1 ENOENT (File o directory non esistente)
statx(AT_FDCWD, "/usr/share/zellij", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0700, stx_size=42, ...}) = 0
mmap(NULL, 548864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x76fee3d19000
mmap(NULL, 585728, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x76fee3c8a000
openat(AT_FDCWD, "/usr/share/zellij/VERSION", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permesso negato)
mkdir("/usr/share/zellij/plugins", 0777) = -1 EACCES (Permesso negato)
statx(AT_FDCWD, "/usr/share/zellij/plugins", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffc642d4060) = -1 EACCES (Permesso negato)
```

I already have plugins in `/usr/share/zellij/plugins` and layouts in `/usr/share/zellij/layouts` because I've installed them with a gentoo ebuild
Also I have a config file in `~/.config/zellij/config.yaml`

```
tree /usr/share/zellij/
/usr/share/zellij/
├── layouts
│   ├── multiple_tabs_layout_htop_command.yaml
│   ├── multiple_tabs_layout.yaml
│   ├── run_htop_layout_with_plugins.yaml
│   └── run_htop_layout.yaml
├── plugins
│   ├── status-bar.wasm
│   ├── strider.wasm
│   └── tab-bar.wasm
└── VERSION
```

### PR DESCRIPTION
**Pull request by a-kenji**
This fixes a regression in the feature system:
The asset installation didn't get turned off by the feature.

fixes #1130

### CODE REVIEW

**Comment by CaptainBloodz** [comment]
My bad,
restarted with new patch file targeting 2 files...

**Comment by CaptainBloodz** [comment]
> My bad, restarted with new patch file targeting 2 files...
Failing to build here on 0.26.0:
New patch fails.
Should I keep the initial pr:
Also fails.

**Comment by CaptainBloodz** [comment]
I'm calming down now...
I see you posted:

[fix(feat): disable mkdir in wasm_wm](https://github.com/zellij-org/zellij/pull/1226/commits/5de635b96ccb7e5a9ff2460e8b422cb1202ea744)

[fixup! fix unused code warnings](https://github.com/zellij-org/zellij/pull/1226/commits/c992073eb5f00c2a1fa5a77f3b46213b1fbde2b0)

Should I keep initial patch?

**Comment by a-kenji** [comment]
@CaptainBloodz 
I don't think you need the initial patch, I put most of the logic into the `install.rs` part now, to encapsulate it.

**Comment by CaptainBloodz** [comment]
Ouch:0.26.0 here.
wasm_vm.rs patches fine BUT:
patching file src/commands.rs
Hunk #1 FAILED at 88.
1 out of 1 hunk FAILED -- saving rejects to file src/commands.rs.rej
patching file src/install.rs

**Comment by CaptainBloodz** [comment]
Failing the same on 0.26.1...

**Comment by a-kenji** [comment]
It gets squashed anyway on merge. So if you want to I can squash it.

**Comment by a-kenji** [comment]
@CaptainBloodz 
Now it should be easier to apply.

**Comment by CaptainBloodz** [comment]
Patching fine with 4 patch files...
Currently building 0.26.0 & debugging gentoo 0.26.1 script...

**Comment by CaptainBloodz** [comment]
```
-------------
patch0.patch
-------------
From 274942849167af41d43e1ceceb116d66f4edcbb2 Mon Sep 17 00:00:00 2001
From: a-kenji <aks.kenji@protonmail.com>
Date: Wed, 16 Mar 2022 21:49:41 +0100
Subject: [PATCH] fix(feat): `disable_automatic_asset_installation`

This fixes a regression in the feature system:
The asset installation didn't get turned off by the feature.

fixes #1130
---
 src/commands.rs | 8 +++++---
 1 file changed, 5 insertions(+), 3 deletions(-)

diff --git a/src/commands.rs b/src/commands.rs
index 542741343..9ecccb0c5 100644
--- a/src/commands.rs
+++ b/src/commands.rs
@@ -88,9 +88,11 @@ fn create_new_client() -> ClientInfo {
 }
 
 fn install_default_assets(opts: &CliArgs) {
-    let data_dir = opts.data_dir.clone().unwrap_or_else(get_default_data_dir);
-    #[cfg(not(disable_automatic_asset_installation))]
-    populate_data_dir(&data_dir);
+    #[cfg(not(feature = "disable_automatic_asset_installation"))]
+    {
+        let data_dir = opts.data_dir.clone().unwrap_or_else(get_default_data_dir);
+        populate_data_dir(&data_dir);
+    }
 }
 
 fn find_indexed_session(

-------------
patch1.patch
-------------
From 5de635b96ccb7e5a9ff2460e8b422cb1202ea744 Mon Sep 17 00:00:00 2001
From: a-kenji <aks.kenji@protonmail.com>
Date: Wed, 16 Mar 2022 22:47:59 +0100
Subject: [PATCH] fix(feat): disable `mkdir` in wasm_wm

The `wasm_vm` creates the `plugin_dir` before mounting it.
Turn that behavior off on `feature-disable-asset-installation`.

Alternative:
    Is this even needed? We make sure the directory is there upon the
    normal asset installation.
---
 zellij-server/src/wasm_vm.rs | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/zellij-server/src/wasm_vm.rs b/zellij-server/src/wasm_vm.rs
index ebea0b8c..326ea012 100644
--- a/zellij-server/src/wasm_vm.rs
+++ b/zellij-server/src/wasm_vm.rs
@@ -92,6 +92,8 @@ pub(crate) fn wasm_thread_main(
     let mut connected_clients: Vec<ClientId> = vec![];
     let plugin_dir = data_dir.join("plugins/");
     let plugin_global_data_dir = plugin_dir.join("data");
+
+    #[cfg(not(feature = "disable_automatic_asset_installation"))]
     fs::create_dir_all(&plugin_global_data_dir).unwrap();
 
     loop {

-------------
patch2.patch
-------------
From c992073eb5f00c2a1fa5a77f3b46213b1fbde2b0 Mon Sep 17 00:00:00 2001
From: a-kenji <aks.kenji@protonmail.com>
Date: Wed, 16 Mar 2022 23:13:59 +0100
Subject: [PATCH] fixup! fix unused code warnings

Caused by conditional compilation.
---
 src/commands.rs | 7 ++-----
 src/install.rs  | 7 +++++++
 2 files changed, 9 insertions(+), 5 deletions(-)

diff --git a/src/commands.rs b/src/commands.rs
index 9ecccb0c5..cfbcb8f08 100644
--- a/src/commands.rs
+++ b/src/commands.rs
@@ -88,11 +88,8 @@ fn create_new_client() -> ClientInfo {
 }
 
 fn install_default_assets(opts: &CliArgs) {
-    #[cfg(not(feature = "disable_automatic_asset_installation"))]
-    {
-        let data_dir = opts.data_dir.clone().unwrap_or_else(get_default_data_dir);
-        populate_data_dir(&data_dir);
-    }
+    let data_dir = opts.data_dir.clone().unwrap_or_else(get_default_data_dir);
+    populate_data_dir(&data_dir);
 }
 
 fn find_indexed_session(
diff --git a/src/install.rs b/src/install.rs
index e7778dde2..41c24d5ac 100644
--- a/src/install.rs
+++ b/src/install.rs
@@ -1,7 +1,10 @@
+#[cfg(not(feature = "disable_automatic_asset_installation"))]
 use std::fs;
 use std::path::Path;
+#[cfg(not(feature = "disable_automatic_asset_installation"))]
 use zellij_utils::{consts::VERSION, shared::set_permissions};
 
+#[cfg(not(feature = "disable_automatic_asset_installation"))]
 macro_rules! asset_map {
     ($($src:literal => $dst:literal),+ $(,)?) => {
         {
@@ -14,6 +17,7 @@ macro_rules! asset_map {
     }
 }
 
+#[cfg(not(feature = "disable_automatic_asset_installation"))]
 pub(crate) fn populate_data_dir(data_dir: &Path) {
     // First run installation of default plugins & layouts
     let mut assets = asset_map! {
@@ -36,3 +40,6 @@ pub(crate) fn populate_data_dir(data_dir: &Path) {
         }
     }
 }
+
+#[cfg(feature = "disable_automatic_asset_installation")]
+pub(crate) fn populate_data_dir(_data_dir: &Path) {}

-------------
patch3.patch
-------------
From 92d4f74b54049b206aca2377b0f98eb1d44d6848 Mon Sep 17 00:00:00 2001
From: a-kenji <aks.kenji@protonmail.com>
Date: Wed, 16 Mar 2022 23:38:06 +0100
Subject: [PATCH] fix(setup): properly show features in setup

---
 Cargo.toml              | 2 +-
 zellij-utils/Cargo.toml | 2 ++
 2 files changed, 3 insertions(+), 1 deletion(-)

diff --git a/Cargo.toml b/Cargo.toml
index 78457fdc..e522a11f 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -64,4 +64,4 @@ bin-dir = "{ bin }{ binary-ext }"
 pkg-fmt = "tgz"
 
 [features]
-disable_automatic_asset_installation = []
+disable_automatic_asset_installation = [ "zellij-utils/disable_automatic_asset_installation" ]
diff --git a/zellij-utils/Cargo.toml b/zellij-utils/Cargo.toml
index 4e837f5a..1e3223dd 100644
--- a/zellij-utils/Cargo.toml
+++ b/zellij-utils/Cargo.toml
@@ -46,3 +46,5 @@ features = ["unstable"]
 [dev-dependencies]
 tempfile = "3.2.0"
 
+[features]
+disable_automatic_asset_installation = [ ]
```
fails as in 0.26.0;
```
RUST_BACKTRACE=full zellij 



















Error occurred in server:
Originating Thread(s):

Error: thread 'wasm' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }': zellij-server/src/wasm_vm.rs:97
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: start_thread
  12: __clone
```

**Comment by a-kenji** [comment]
Could you check please with `zellij setup --check` again if the feature is active?

**Comment by CaptainBloodz** [comment]
Rebuilding with all-in-one single patch file...

**Comment by CaptainBloodz** [comment]
0.26.0:
```
RUST_BACKTRACE=full zellij 

Error occurred in server:
Originating Thread(s):
1. ipc_server: NewClient
2. pty_thread: NewTab
3. screen_thread: NewTab
4. plugin_thread: Load

Error: thread 'wasm' panicked at 'Cannot resolve wasm bytes for plugin PluginConfig { path: "tab-bar", run: Pane(None), _allow_exec_host_cmd: false, location: Zellij(PluginTag("tab-bar")) }': zellij-server/src/wasm_vm.rs:252
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: start_thread
  12: __clone
```

**Comment by CaptainBloodz** [comment]
```
zellij setup --check
[Version]: "0.26.0"
[CONFIG DIR]: Not Found
 On your system zellij looks in the following config directories by default:
 "/home/luc/.config/zellij"
 "/etc/zellij"
[CONFIG FILE]: Not Found
 By default zellij looks for a file called [config.yaml] in the configuration directory
[DATA DIR]: "/usr/share/zellij"
[PLUGIN DIR]: "/usr/share/zellij/plugins"
[LAYOUT DIR]: Not Found
[SYSTEM DATA DIR]: "/usr/share/zellij"
[ARROW SEPARATOR]: 
 Is the [ARROW_SEPARATOR] displayed correctly?
 If not you may want to either start zellij with a compatible mode: 'zellij options --simplified-ui true'
 Or check the font that is in use:
 https://zellij.dev/documentation/compatibility.html#the-status-bar-fonts-dont-render-correctly
[MOUSE INTERACTION]: 
 Can be temporarily disabled through pressing the [SHIFT] key.
 If that doesn't fix any issues consider to disable the mouse handling of zellij: 'zellij options --disable-mouse-mode'
[FEATURES]: ["disable_automatic_asset_installation"]
[DOCUMENTATION]: zellij.dev/documentation
```

**Comment by a-kenji** [comment]
Do you have the tab bar located in `/usr/share/zellij/plugins/tab-bar.wasm`?

**Comment by CaptainBloodz** [comment]
```
efil zellij
 * Searching for zellij ...
 * Contents of app-misc/zellij-0.26.0:
/usr
/usr/bin
/usr/bin/zellij
/usr/share
/usr/share/bash-completion
/usr/share/bash-completion/completions
/usr/share/bash-completion/completions/zellij
/usr/share/doc
/usr/share/doc/zellij-0.26.0
/usr/share/doc/zellij-0.26.0/ARCHITECTURE.md.lzma
/usr/share/doc/zellij-0.26.0/CHANGELOG.md.lzma
/usr/share/doc/zellij-0.26.0/MANPAGE.md.lzma
/usr/share/doc/zellij-0.26.0/README.md.lzma
/usr/share/doc/zellij-0.26.0/TERMINOLOGY.md.lzma
/usr/share/doc/zellij-0.26.0/THIRD_PARTY_INSTALL.md.lzma
/usr/share/fish
/usr/share/fish/vendor-completions
/usr/share/fish/vendor-completions/_zellij
/usr/share/fish/vendor_completions.d
/usr/share/fish/vendor_completions.d/zellij.fish
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/zellij.1.lzma
/usr/share/xsessions
/usr/share/xsessions/zellij.desktop
/usr/share/zellij
/usr/share/zellij/layouts
/usr/share/zellij/layouts/multiple_tabs_layout.yaml
/usr/share/zellij/layouts/multiple_tabs_layout_htop_command.yaml
/usr/share/zellij/layouts/run_htop_layout.yaml
/usr/share/zellij/layouts/run_htop_layout_with_plugins.yaml
/usr/share/zellij/plugins
/usr/share/zellij/plugins/status-bar.wasm
/usr/share/zellij/plugins/strider.wasm
/usr/share/zellij/plugins/tab-bar.wasm
```

**Comment by CaptainBloodz** [comment]
```
amd64 ~ # ll /usr/share/zellij
total 12
drwxr-xr-x 2 root root 4096 mars  17 02:53 layouts
drwx------ 2 root root 4096 mars  17 02:53 plugins
-rw-r--r-- 1 root root    6 mars  16 22:11 VERSION
amd64 ~ # ll /usr/share/zellij/*
-rw-r--r-- 1 root root    6 mars  16 22:11 /usr/share/zellij/VERSION

/usr/share/zellij/layouts:
total 16
-rw-r--r-- 1 root root 1808 mars  17 02:51 multiple_tabs_layout_htop_command.yaml
-rw-r--r-- 1 root root 1748 mars  17 02:51 multiple_tabs_layout.yaml
-rw-r--r-- 1 root root  813 mars  17 02:51 run_htop_layout_with_plugins.yaml
-rw-r--r-- 1 root root  464 mars  17 02:51 run_htop_layout.yaml

/usr/share/zellij/plugins:
total 1540
-rw-r--r-- 1 root root 545028 mars  17 02:51 status-bar.wasm
-rw-r--r-- 1 root root 581122 mars  17 02:51 strider.wasm
-rw-r--r-- 1 root root 444257 mars  17 02:51 tab-bar.wasm
```

**Comment by a-kenji** [comment]
Could you try changing your plugin config to:
```
plugins:
    - path: /usr/share/zellij/plugins/tab-bar.wasm
      tag: tab-bar
    - path: /usr/share/zellij/plugins/status-bar.wasm
      tag: status-bar
    - path: /usr/share/zellij/plugins/strider.wasm
      tag: strider
```

Thanks for all the help so far! I think we are getting very close.

**Comment by CaptainBloodz** [comment]
```
find . -name Cargo.toml
./Cargo.toml
./zellij-utils/Cargo.toml
./zellij-tile/Cargo.toml
./zellij-tile-utils/Cargo.toml
./zellij-server/Cargo.toml
./zellij-client/Cargo.toml
./default-plugins/tab-bar/Cargo.toml
./default-plugins/strider/Cargo.toml
./default-plugins/status-bar/Cargo.toml
```
Which one?

**Comment by a-kenji** [comment]
```
mkdir ~/.config/zellij
zellij setup --dump-config > ~/.config/zellij/config.yaml
```

**Comment by CaptainBloodz** [comment]
> ```
> amd64 ~ # ll /usr/share/zellij
> total 12
> drwxr-xr-x 2 root root 4096 mars  17 02:53 layouts
> drwx------ 2 root root 4096 mars  17 02:53 plugins
> -rw-r--r-- 1 root root    6 mars  16 22:11 VERSION
> amd64 ~ # ll /usr/share/zellij/*
> -rw-r--r-- 1 root root    6 mars  16 22:11 /usr/share/zellij/VERSION
> 
> /usr/share/zellij/layouts:
> total 16
> -rw-r--r-- 1 root root 1808 mars  17 02:51 multiple_tabs_layout_htop_command.yaml
> -rw-r--r-- 1 root root 1748 mars  17 02:51 multiple_tabs_layout.yaml
> -rw-r--r-- 1 root root  813 mars  17 02:51 run_htop_layout_with_plugins.yaml
> -rw-r--r-- 1 root root  464 mars  17 02:51 run_htop_layout.yaml
> 
> /usr/share/zellij/plugins:
> total 1540
> -rw-r--r-- 1 root root 545028 mars  17 02:51 status-bar.wasm
> -rw-r--r-- 1 root root 581122 mars  17 02:51 strider.wasm
> -rw-r--r-- 1 root root 444257 mars  17 02:51 tab-bar.wasm
> ```

Isn't there a right issue on .../plugins dir and/or content?

Once config.yaml modified:
```
RUST_BACKTRACE=full zellij 

Error occurred in server:
Originating Thread(s):
1. ipc_server: NewClient
2. pty_thread: NewTab
3. screen_thread: NewTab
4. plugin_thread: Load

Error: thread 'wasm' panicked at 'Cannot resolve wasm bytes for plugin PluginConfig { path: "tab-bar", run: Pane(None), _allow_exec_host_cmd: false, location: Zellij(PluginTag("tab-bar")) }': zellij-server/src/wasm_vm.rs:252
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: start_thread
  12: __clone
```
```

**Comment by CaptainBloodz** [comment]
```
luc@amd64 ~ $ zellij setup --check
[Version]: "0.26.0"
[CONFIG DIR]: "/home/luc/.config/zellij"
[CONFIG FILE]: "/home/luc/.config/zellij/config.yaml"
[CONFIG FILE]: Well defined.
[DATA DIR]: "/usr/share/zellij"
[PLUGIN DIR]: "/usr/share/zellij/plugins"
[LAYOUT DIR]: "/home/luc/.config/zellij/layouts"
[SYSTEM DATA DIR]: "/usr/share/zellij"
[ARROW SEPARATOR]: 
 Is the [ARROW_SEPARATOR] displayed correctly?
 If not you may want to either start zellij with a compatible mode: 'zellij options --simplified-ui true'
 Or check the font that is in use:
 https://zellij.dev/documentation/compatibility.html#the-status-bar-fonts-dont-render-correctly
[MOUSE INTERACTION]: 
 Can be temporarily disabled through pressing the [SHIFT] key.
 If that doesn't fix any issues consider to disable the mouse handling of zellij: 'zellij options --disable-mouse-mode'
[FEATURES]: ["disable_automatic_asset_installation"]
[DOCUMENTATION]: zellij.dev/documentation
```
```
luc@amd64 ~ $ ll /home/luc/.config/zellij/layouts
ls: cannot access '/home/luc/.config/zellij/layouts': Aucun fichier ou dossier de ce type
```

**Comment by a-kenji** [comment]
@CaptainBloodz 

Do you mind trying to run it with:

```
zellij --data-dir /usr/share/zellij
```

**Comment by CaptainBloodz** [comment]
zellij --data-dir /usr/share/zellij



















Error occurred in server:
Originating Thread(s):
1. ipc_server: NewClient
2. pty_thread: NewTab
3. screen_thread: NewTab
4. plugin_thread: Load

Error: thread 'wasm' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }': zellij-server/src/wasm_vm.rs:275
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: start_thread
  13: __clone

**Comment by a-kenji** [comment]
Thank you! Do you mind trying again with the `data_dir` flag and the new build?

**Comment by a-kenji** [comment]
> luc@amd64 ~ $ ll /home/luc/.config/zellij/layouts

This is to be expected. The `layout_dir` per default is a subdirectory of the Config directory. So if the config directory is there we know where we can look for the `layout_dir` even though it is not there yet.

**Comment by CaptainBloodz** [comment]
> Thank you! Do you mind trying again with the `data_dir` flag and the new build?

Plz confitm those two patches,
[e4cc8bc](https://github.com/zellij-org/zellij/pull/1226/commits/e4cc8bc1e6b029ba7c61b12b60fc2916bd181157)

[3506ca5](https://github.com/zellij-org/zellij/pull/1226/commits/3506ca50de0ab5443479011e44f750845f6bf5e1)

Are additional to all-in-one patch file, or should new ones should replace parts in all-in-one?

> Do you mind trying again with the data_dir ?
Elaborate, plz.

> New ebuild
Currently checking about that, as it is out of tree...

**Comment by CaptainBloodz** [comment]
Currently building all-in-one+2 new patches...
Think I got it about data_dir on command line...

**Comment by CaptainBloodz** [comment]
```
luc@amd64 ~ $ rm ~/.config/zellij -rf
luc@amd64 ~ $ mkdir ~/.config/zellij
luc@amd64 ~ $ zellij setup --dump-config > ~/.config/zellij/config.yaml
luc@amd64 ~ $ zellij --data-dir /usr/share/zellij

Error occurred in server:
Originating Thread(s):
1. ipc_server: NewClient
2. pty_thread: NewTab
3. screen_thread: NewTab
4. plugin_thread: Load

Error: thread 'wasm' panicked at 'called `Result::unwrap()` on an `Err` value: PreopenedDirectoryNotFound("/usr/share/zellij/plugins/data/zellij:tab-bar")': zellij-server/src/wasm_vm.rs:289
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: start_thread
  13: __clone
```

**Comment by CaptainBloodz** [comment]
Rebuild with all-in-one + 2 patches + [1d46a86](https://github.com/zellij-org/zellij/pull/1226/commits/1d46a86a9366116e7d2f0c326f5035aad620d5a0) queued.
It that right?

**Comment by a-kenji** [comment]
@CaptainBloodz Yes!

**Comment by CaptainBloodz** [comment]
Current compilation snippet:
'''
   Compiling zellij-server v0.26.0 (/var/tmp/portage/app-misc/zellij-0.26.0/work/zellij-0.26.0/zellij-server)
warning: unused variable: `plugin_global_data_dir`
   --> zellij-server/src/wasm_vm.rs:241:5
    |
241 |     plugin_global_data_dir: &Path,
    |     ^^^^^^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_plugin_global_data_dir`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: `zellij-server` (lib) generated 1 warning
   Compiling zellij v0.26.0 (/var/tmp/portage/app-misc/zellij-0.26.0/work/zellij-0.26.0)
'''

**Comment by CaptainBloodz** [comment]
Working here, without any ~/.config/zellij dir.
Nice :)
```
luc@amd64 ~ $ zellij
Bye from Zellij!
```

**Pull request merged**
