### PR TITLE
Add Option for Simplified Layout

### LINKED ISSUE #313: More lightline like toolbars [Feature Request]
I have a very minimal set up.

When I open the multiplexer this is what my toolbar looks like.

image

I would like to request a simplified version that does not have the font/glyph deps. Something like a light line option (see https://github.com/itchyny/lightline.vim)

image

### PR DESCRIPTION
**Pull request by a-kenji**
* the simplified layout omits the Nerdfonts characters that are not
  found in every Fontset

* add an optional config option to opt into the simplified ui
  `simplified_ui: bool`

* add a config flag that allows opting into the simplified ui
  `zellij options --simplified-ui`

* move the `clean` flag to the `setup` subcommand

Closes #313.

### CODE REVIEW

**Comment by a-kenji** [comment]
We always noticed them as dependencies, we just haven't had a good way of requesting a simpler layout yet. Thanks for the suggestion, that is a good idea!

**Comment by a-kenji** [comment]
@TheLostLambda 
Would it make sense to let people choose the separator character?
Or is that something that shouldn't be propagated?

**Comment by alexhallam** [comment]
@a-kenji I personally did not see much value in separators. The colors/layout/highlighting in zellij seemed sufficient to me. This is a subjective opinion.

**Comment by a-kenji** [comment]
That is indeed a little odd.
Do you mind checking:
```
zellij --version
```
and 
```
zellij options --help
```
please also try 
```
zellij option --help
```
Thank you!

**Comment by alexhallam** [comment]
Just want to let you know I just downloaded the most recent version. Everything is working great. Thanks for implementing this.

**Pull request merged**
