### PR TITLE
feature(strider): Show current parent folder

### PR DESCRIPTION
**Pull request by a-kenji**
#195

Shows the current parent folder, if opened inside
of strider eg:

It doesn't display the current folder on the root
pane of strider, but if opened a sub folder it displays
the parent folder.

image
image

### CODE REVIEW

**Comment by imsnif** [comment]
Awesome! Right now this seems a little unclear to me visually though. Even knowing what I was looking for, I had a bit of a hard time finding it. Do you think we can make the path clearer? Maybe make it a different color and/or add some background to it, or add some spacing between it and the folder list, or...? I trust your creativity on this one. :)

**Comment by a-kenji** [comment]
Yes that is true! It already has a little different styling but it does blend in with everything else.
I will try to iterate on it a little and see If I find something I am comfortable with! Thanks for the feedback!

**Comment by a-kenji** [comment]
@imsnif 
20210402_14h50m58s_grim

Does that make more sense?The header is now underlined and thus separated from the files.

**Comment by imsnif** [comment]
Hum... I think it's a good direction but my preference would be to differentiate it by color. We took a lot of inspiration from the ranger tool - maybe check out what they do to get some ideas?

**Comment by a-kenji** [comment]
Ah yeah, a different colour may be a good delineation.
Ranger has a hierarchical paradigm, so it still works a little bit different and can
display the parent folder more naturally:
20210405_11h43m38s_grim

**Pull request closed without merging**
