### PR TITLE
Adds create option to attach

### LINKED ISSUE #541: Feature request: zellij attach --create
A command that automatically creates (if it doesn't exist) and joins the given named-session would be useful.

It can come in handy in creating quick project-specific sessions, for instance:

```
zellij attach --create $(basename `pwd`)
```

### PR DESCRIPTION
**Pull request by pedrohjordao**
- Adds create option to attach that will create a new session if one doesn't already exists with the given name
- Small refactor to remove code duplication

Closes #541

### CODE REVIEW

**Review by kunalmohan — CHANGES_REQUESTED** [review]
Hey @pedrohjordao! Thank you for taking this up 🙂! It is a much-needed feature.
This PR is going in the right direction, but there are a couple of cases that need to be handled differently. I've mentioned them below. Let me know if more clarifications are needed.

**Comment by pedrohjordao** [comment]
Thanks, I'll take your comments and update the pr soon

**Comment by pedrohjordao** [comment]
Just a heads up: I still plan on working on this, but I'm in the middle of a change of jobs and country, so it might take a couple of weeks until a can pick this up again. If anyone wants to work on it, feel free.

**Comment by a-kenji** [comment]
Thank you for the work on this feature!
It has now been implemented by #731.

**Pull request closed without merging**
