### PR TITLE
Edit scrollback

### PR DESCRIPTION
**Pull request by cosminadrianpopescu**
PR for #1403

### CODE REVIEW

**Comment by imsnif** [comment]
@a-kenji - any clues as to why the nix build is failing?

**Comment by a-kenji** [comment]
@imsnif,
I assume this is because the `Cargo.lock` file is in a weird state.
`cargo update` and committing the lock file might alleviate this issue,
If not I think I can look more into this tomorrow.

**Comment by imsnif** [comment]
@a-kenji - FYI, it works now. The `Cargo.lock` was updated from a local build (I update and push it all the time as I'm building, testing manually and running tests). What fixed this was merging from main and then building (which indeed included a change to the Cargo.lock file over the one from this branch). Could it be that the nix test uses some sort of external state combined with main?

**Comment by imsnif** [comment]
Thank you for your excellent work on this @cosminadrianpopescu - I'm stoked about this feature and think many others will be as well! Hope to see more contributions from you - even if Rust might not be your cup of tea :)

**Comment by cosminadrianpopescu** [comment]
> Thank you for your excellent work on this

You welcome.

> I'm stoked about this feature and think many others will be as well! 

I also think it's a killer feature. This would be enough to make me switch from tmux. And I never had any big issues with tmux's find and copy paste. Just small annoyances. But to be able to open all that buffer in `vim`, it cannot be beaten by any paradigm impementation. `vim` is the best at this kind of things. 

> Hope to see more contributions from you

I was thinking now of finishing this by adding a nice name to the editor panel, like we discussed. Then I was thinking at looking into the buffer's rename (what we discussed before this: adding an option to keep the tab's shortcuts and by default re-naming the tabs when closing one of the tabs which is not the last one). What do you think?

> even if Rust might not be your cup of tea

Yeah... I can see the advantages, and I can understand if someone wants to program something for routers for example (with limited resources). But for doing something in the user space (no matter how low level), I think a garbage collector is really nothing compared with a steep learning curve. I think that this steep learning curve is going to make a lot of people just not want to contribute.

**Comment by imsnif** [comment]
> I was thinking now of finishing this by adding a nice name to the editor panel, like we discussed. Then I was thinking at looking into the buffer's rename (what we discussed before this: adding an option to keep the tab's shortcuts and by default re-naming the tabs when closing one of the tabs which is not the last one). What do you think?

Sounds great.

**Comment by a-kenji** [comment]
@cosminadrianpopescu 
I agree, this is awesome, thanks for all the work.

@imsnif,
The `nix build` shouldn't use external state from main, but it might be possible, I will look into it a bit more.
Basically it uses the nix files, the `Cargo.toml`, `Cargo.lock` and the `rust-toolchain.toml`, which should be contained inside the branch.

**Pull request merged**
