### PR TITLE
fix(server): fix leakage of SessionMetaData

### PR DESCRIPTION
**Pull request by tw4452852**
Currently, when the server exits, Session data is leaked because 'server_listener' thread still holds a reference to it.
Due to this thread blocking on the socket accepting, to fix this problem, we change it to polling mode (the timer interval is 10 milliseconds) and add a flag to indicate exit.

Signed-off-by: Tw <tw19881113@gmail.com>

### CODE REVIEW

**Comment by kunalmohan** [comment]
@tw4452852 Thanks for catching this! I'm a bit curious about how big of an issue this is and whether there is an alternate approach to solve this. This only happens when zellij is exiting and IIUC the OS releases any memory allocated to a process after it exits.

The reason I'm concerned is that the new change adds polling to the thread so the thread will wake up every 10ms. We had a similar polling approach in some other section of zellij in some of the earlier releases due to which users complained of higher CPU and power consumption (Linked Issue: https://github.com/zellij-org/zellij/issues/509).

**Comment by tw4452852** [comment]
Hi @kunalmohan 

Indeed, any allocated memory will be released by the OS when the process exits. But as I did [some temporary files cleanup](https://github.com/zellij-org/zellij/pull/723/files#diff-72baa051cbfabfc51139227f2a7a27671782c29e1e29537326fef9614e945ef9R171) in PR #723 when `wasm` thread exits. And this depends on the notification sent when `SessionMetaData` drops:

https://github.com/zellij-org/zellij/blob/72b0474d024abc799a2f5e90a1078f68b150502a/zellij-server/src/lib.rs#L106

Regarding the CPU usage when polling, it's almost ignorable compared to the blocking mode. As I use this during my daily work.

**Comment by imsnif** [comment]
I hope it's okay if I chime in here: if this is in order to facilitate something else that hasn't been merged yet, maybe we can look into that first and then see if we still need this one? I guess @TheLostLambda will probably have some useful input regarding cached plugin disk metadata.

**Comment by kunalmohan** [comment]
FWIW we drop the `SessionMetaData` object on exit here: https://github.com/zellij-org/zellij/blob/72b0474d024abc799a2f5e90a1078f68b150502a/zellij-server/src/lib.rs#L270
But there are other cases where we don't drop it on exit ([this](https://github.com/zellij-org/zellij/blob/72b0474d024abc799a2f5e90a1078f68b150502a/zellij-server/src/lib.rs#L288) and [this](https://github.com/zellij-org/zellij/blob/72b0474d024abc799a2f5e90a1078f68b150502a/zellij-server/src/lib.rs#L296)). So maybe we can move the above statement outside the loop, before:
https://github.com/zellij-org/zellij/blob/72b0474d024abc799a2f5e90a1078f68b150502a/zellij-server/src/lib.rs#L300-L304

**Comment by tw4452852** [comment]
Ah, I see!

**Comment by tw4452852** [comment]
BTW, after re-reading the code, I think the second clone is unnecessary:

https://github.com/zellij-org/zellij/blob/72b0474d024abc799a2f5e90a1078f68b150502a/zellij-server/src/lib.rs#L167-L187

Correct me if I'm wrong.

**Comment by kunalmohan** [comment]
@tw4452852 yes, you are right!

**Comment by tw4452852** [comment]
Thanks @kunalmohan 

I have updated the patch according to your suggestions.

**Review by kunalmohan — APPROVED** [review]
LGTM! Thanks!!

**Pull request merged**
