### PR TITLE
New feature: Synchronize text sent to panes

### LINKED ISSUE #302: Implement functionality propagate (sync) all panes either type or paste text
I would like to ask you to implement functionality propagate to all panes to type or paste text to all active
windows. It is usefull, when you have open multiple ssh session to systems and you want to execute same
command on all of them. It's similar as is implemented in tmux. 
[Here is example with video](https://blog.sanctum.geek.nz/sync-tmux-panes/)
Thank you.

### PR DESCRIPTION
**Pull request by dantepippi**
Creating a new keybinding "s" on the Pane mode. When sync is enabled text will be sent to all terminals on the current tab.

Closes #302

### CODE REVIEW

**Review by khs26 — APPROVED** [review]
Looks great!

I don't think it needs addressing as part of this PR, but I think there are a couple of future extensions - could you create issues for them?

1) Controlling which panes in a tab are in sync mode - this could be particularly useful if one of the panes is a plugin, which wouldn't expect to handle the same input as a regular pane.
2) Highlighting which panes are in sync mode (with a green border, like the active pane).

I particularly like that you've considered the UI by adding the "Sync" label to the tab.

**Comment by a-kenji** [comment]
Thank you, this looks great!
The default keybindings are now solely defined under `/assets/config/default.yaml`

**Comment by dantepippi** [comment]
> Looks great!
Thanks for the feedback and taking your time to review my code!
> 
> I don't think it needs addressing as part of this PR, but I think there are a couple of future extensions - could you create issues for them?
> 
>     1. Controlling which panes in a tab are in sync mode - this could be particularly useful if one of the panes is a plugin, which wouldn't expect to handle the same input as a regular pane.

So far I don't replicate the text on plugin panes, only to regular panes. How do you imagine the UI for selecting which panes are in sync? I think being able to sync all panes at once is a nice feature and should also be a choice.

> 
>     2. Highlighting which panes are in sync mode (with a green border, like the active pane).
> 
> 
> I particularly like that you've considered the UI by adding the "Sync" label to the tab.

**Comment by TheLostLambda** [comment]
Hey @dantepippi! This is a super sick change that's got great code and adds a great feature! Thanks for fixing the merge conflicts!

I'll merge this now and add it to the changelog for you :slightly_smiling_face: 

Thanks for the awesome PR!

**Pull request merged**
