### PR TITLE
Doc build

### PR DESCRIPTION
**Pull request by a-kenji**
To inform people about the `binaryen` dependency.

### CODE REVIEW

**Comment by imsnif** [comment]
I think this is no longer the case, right @TheLostLambda ?

**Comment by TheLostLambda** [comment]
It might still be worth mentioning, as wasm-opt is used if available, but you're right that it's not *needed* anymore!

**Comment by a-kenji** [comment]
Oh, I thought I pushed the revised version already.

**Review by imsnif — APPROVED** [review]
Thanks!

**Pull request merged**
