### PR TITLE
fix: set sticky bit on socket

### LINKED ISSUE #2080: zellij sessions sockets may get deleted
zellij places its server sockets in XDG_RUNTIME_DIR.
Per specification*, this directory may be cleaned of old files periodically, and I suspect at least one user on discord lost access to his session this way.
The problem can be solved in two ways, ideally we do both:
- set the sticky bit on the socket file to avoid automatic cleanup *
- provide a method to recreate the socket file, e.g. on SIGUSR1

*Sources:
https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

### PR DESCRIPTION
**Pull request by tlinford**
Hopefully resolve #2080.

@imsnif I'm not sure if this actually solves the problem, but I don't really see any downside to this either, what do you think?

### CODE REVIEW

**Comment by imsnif** [comment]
I don't have a lot of context on this... what does @raphCode think?

**Comment by raphCode** [comment]
as per the freedesktop spec, this should prevent automatic cleanup.
However, socket files can still be deleted manually or by accident - maybe we can provide a way of recreating the socket file of a running server? This way "lost" sessions may be recovered.

**Comment by imsnif** [comment]
> maybe we can provide a way of recreating the socket file of a running server? This way "lost" sessions may be recovered.

This is a cool feature to have, but very much not trivial to implement. I vote for not compounding it with this one.

**Comment by imsnif** [comment]
Hey, what's the status here?

**Comment by imsnif** [comment]
@tlinford (for when you get back) - afaict, the sticky bit should only apply to directories and not files... are we sure we're doing the right thing here?

**Comment by tlinford** [comment]
Forgot to answer here sorry, the freedesktop spec says: 'To ensure that your files are not removed, they should have their access time timestamp modified at least once every 6 hours of monotonic time or the 'sticky' bit should be set on the file.'

I also found that wezterm does this (notice the T attr):
```
❯ ll /run/user/1000/wezterm/
srwx-----T thomas thomas  0 B Wed Mar 29 10:11:49 2023  gui-sock-35301=
lrwxrwxrwx thomas thomas 37 B Wed Mar 29 10:11:49 2023  wayland-wayland-1-org.wezfurlong.wezterm@ ⇒ /run/user/1000/wezterm/gui-sock-35301
```

**Comment by imsnif** [comment]
Cool, thanks for looking into this @tlinford . Anything else we need to do here or are waiting for?

**Pull request merged**
