### PR TITLE
update the pane name when editing a  buffer

### PR DESCRIPTION
**Pull request by cosminadrianpopescu**
This pull request should update the pane editing a buffer.

### CODE REVIEW

**Comment by cosminadrianpopescu** [comment]
I see also a test failing. I will fix it.

**Comment by cosminadrianpopescu** [comment]
@imsnif So, I see that the tests are failing because of the title being different. Can you please explain me how the snapshot assertion is working?

**Comment by imsnif** [comment]
Hey, @cosminadrianpopescu I'm sorry for not responding but I'm going on vacation and don't have a lot of time. I'll be back around June 24th and can reply in more detail then. Until then, there's some information about the tests in `CONTRIBUTING.md` - we generally use snapshot tests created with `cargo insta`.

**Comment by cosminadrianpopescu** [comment]
Hello @imsnif and the others. I'm back from holidays and I will start working again on zellij. Meanwhile I will open a bug report.

**Comment by imsnif** [comment]
Hey, what's the status of this?

**Comment by imsnif** [comment]
Already implemented

**Pull request closed without merging**
