### PR TITLE
Fix SGR/UTF8 mouse reporting in terminal panes

### PR DESCRIPTION
**Pull request by imsnif**
This is a fix for: https://github.com/zellij-org/zellij/issues/1633

Main changes:
1. We now track which mouse button was released when collecting user input (rather than sending a generic "release" event on to the zellij server).
2. DECSET/DECRST now loop through all arguments rather than just taking the first one (oops!)
3. Mouse mode is now tracked as "NoEncoding", "SGR" or "UTF8" rather than true/false
4. We now also track the mouse tracking method as "Off", "Normal" and "ButtonEventTracking", reporting nothing, button press + release and button press + release + hold respectively.
5. We send the relevant events from 4 with the relevant encoding from 3 to the terminal panes as needed. Defaulting to utf8 encoding.

There's room to implement AnyEvent tracking in supported terminals, but that's out of scope for this PR.

### CODE REVIEW

**Comment by imsnif** [comment]
@tlinford - if you could give this a spin to make sure I didn't break any mouse stuff that I'm not aware of that would be great :)

@AutumnMeowMeow - if you have the time and feel like it, would you like to check this change out and let me know what you think?

**Comment by AutumnMeowMeow** [comment]
@imsnif Testing inside vttest, I see the following issues:

* Off-by-one coordinates: SGR mode (1006), button-event (1002), during a drag-with-button-down: the coordinates are incorrectly +1 rows +1 cols.  The button-down and button-up coordinates are correct.
* Off-by-one coordinates: UTF8 mode (1005), normal-event (1000), during a button-release: the coordinates are incorrectly +1 rows +1 cols.  The button-down coordinates are correct.
* Off-by-one coordinates: UTF8 mode (1005), button-event (1002), during a button-release and during a drag-with-button-down: the coordinates are incorrectly +1 rows +1 cols.  The button-down coordinates are correct.
* When a test is exited via 'q', mouse tracking is still on and not off.  You are missing the corresponding cases [from here](https://github.com/zellij-org/zellij/blob/fix-mouse-reporting/zellij-server/src/panes/grid.rs#L2345) for 1000, 1002, 1003 (TBD) that belong [here](https://github.com/zellij-org/zellij/blob/1b2e52cfc323be0f8414af7010a4fd53e87da8ab/zellij-server/src/panes/grid.rs#L2270).

**Comment by imsnif** [comment]
Thanks @AutumnMeowMeow ! I guess I was pretty tired when I submitted this. I even glanced over these in the tests :) All fixed.

**Comment by AutumnMeowMeow** [comment]
@imsnif It's better now, but I still see the following:

* Button 2 (usually middle button) is not reporting on button-down or button-down-and-drag, but is reporting on button-up/release.
* In SGR coordinates, when button 2 reports button-up, it incorrectly reports it as button 1 (code 0) button-up.
* In both UTF-8 and SGR coordinates, button-down-and-drag is not being reported as a drag (button code + 32), but rather as button-down (button code).

**Comment by imsnif** [comment]
@AutumnMeowMeow - all fixed. These were part misunderstanding on my part, and part Zellij not previously fully supporting middle-clicks. Thanks again!

**Comment by tlinford** [comment]
@imsnif gave it a test, all of these seem fine to me:

- pane/tab selection with mouse
- moving floating pane
- selecting text
- scrolling with mouse wheel
- interacting with nvim with `set mouse=a`

**Comment by AutumnMeowMeow** [comment]
I confirm normal-event and button-event are working correctly for me:

https://user-images.githubusercontent.com/99296476/184955817-b1c97eff-e816-4746-a251-2bcd46533714.mp4

Any-event is not yet working, so no tracking mouse cursor tracking, but that is expected.  Click/drag/release and wheel-up/wheel-down are working well.

I would say #1633 is fixed with this. :)

**Comment by imsnif** [comment]
Fantastic! Thank you both for your help.

**Pull request merged**
