### PR TITLE
fix: catch and report errors about tty I/O (#882)

### LINKED ISSUE #882: Crash when exiting shell
**Basic information**

`zellij --version`: 0.21.0 / 0.20.1 (crash happens with both)
`uname -av`: Linux skydragon 5.15.2-arch1-1 #1 SMP PREEMPT Fri, 12 Nov 2021 19:22:10 +0000 x86_64 GNU/Linux

**Further information**
This only happens on my vserver, I cannot reproduce locally. Happens via ssh oder tty accessed via hoster's VNC feature.
This is a fairly slow CPU server, and I had already problems with earlier zellij builds there, but I don't know anymore.
The issue seems this exact machine.

Reproduction steps:
1. open `zellij`
2. (optional) add new pane or tab so that zellij should keep open after closing a pane
3. Press `Ctrl-D` or type `exit` to quit the shell
4. Crash in 99% of the time

Backtrace for debug build of the tree at the commit https://github.com/zellij-org/zellij/commit/639566df1540b2a80f6fdf27d7eb2ce823fa03e5:

<details> 
  <summary>Click to expand:</summary>

```
Error occurred in server:
Originating Thread(s):
1. stdin_handler_thread: AcceptInput
2. screen_thread: WriteCharacter

Error: thread 'screen' panicked at 'failed to drain terminal: Sys(EBADF)': zellij-server/src/tab.rs:719
   0: zellij_utils::errors::handle_panic
             at zellij/zellij-utils/src/errors.rs:25:21
   1: zellij_server::start_server::{{closure}}
             at zellij/zellij-server/src/lib.rs:201:13
   2: std::panicking::rust_panic_with_hook
             at /rustc/1.56.1/library/std/src/panicking.rs:628:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/1.56.1/library/std/src/panicking.rs:521:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/1.56.1/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/1.56.1/library/std/src/panicking.rs:517:5
   6: core::panicking::panic_fmt
             at /rustc/1.56.1/library/core/src/panicking.rs:101:14
   7: core::result::unwrap_failed
             at /rustc/1.56.1/library/core/src/result.rs:1617:5
   8: core::result::Result<T,E>::expect
             at /rustc/1.56.1/library/core/src/result.rs:1259:23
   9: zellij_server::tab::Tab::write_to_pane_id
             at zellij/zellij-server/src/tab.rs:717:17
  10: zellij_server::tab::Tab::write_to_active_terminal
             at zellij/zellij-server/src/tab.rs:707:9
  11: zellij_server::screen::screen_thread_main
             at zellij/zellij-server/src/screen.rs:670:30
  12: zellij_server::init_session::{{closure}}
             at zellij/zellij-server/src/lib.rs:569:17
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/1.56.1/library/std/src/sys_common/backtrace.rs:125:18
  14: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/1.56.1/library/std/src/thread/mod.rs:481:17
  15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/1.56.1/library/core/src/panic/unwind_safe.rs:271:9
  16: std::panicking::try::do_call
             at /rustc/1.56.1/library/std/src/panicking.rs:403:40
  17: __rust_try
  18: std::panicking::try
             at /rustc/1.56.1/library/std/src/panicking.rs:367:19
  19: std::panic::catch_unwind
             at /rustc/1.56.1/library/std/src/panic.rs:129:14
  20: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/1.56.1/library/std/src/thread/mod.rs:480:30
  21: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/1.56.1/library/core/src/ops/function.rs:227:5
  22: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/1.56.1/library/alloc/src/boxed.rs:1636:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/1.56.1/library/alloc/src/boxed.rs:1636:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/1.56.1/library/std/src/sys/unix/thread.rs:106:17
  23: start_thread
  24: __GI___clone
```

</details>

### PR DESCRIPTION
**Pull request by raphCode**
I tried to fix #882 by logging the corresponding errors instead of crashing.
This is a quick fix of the symptoms (server crash), and does not clear the underlying issue (I suspect a race condition around the tty file descriptor handling).
I am not experienced enough in the codebase to resolve the race condition, but I may look into it if someone gives me directions.

More details are in the github issue and in the commit message (if someone `git blame`s someday in the future).

### CODE REVIEW

**Comment by raphCode** [comment]
Thanks for running the CI.
An e2e test failed, I don't know why and it really shouldn't because of this small logging change.
Since my fork was 39 commits behind, I merged the new changes in, hoping this may fix it.

Please approve the CI again.

**Comment by tlinford** [comment]
> I tried to fix #882 by logging the corresponding errors instead of crashing. This is a quick fix of the symptoms (server crash), and does not clear the underlying issue (I suspect a race condition around the tty file descriptor handling). I am not experienced enough in the codebase to resolve the race condition, but I may look into it if someone gives me directions.
> 
> More details are in the github issue and in the commit message (if someone `git blame`s someday in the future).

Looked a bit more into this, and also do not know how to properly fix this at the moment, I suspect some pretty big changes would be necessary.
This fix seems very reasonable for now though :+1:

**Comment by raphCode** [comment]
Yay, my first merged PR :heart:

> I suspect some pretty big changes would be necessary.

Out of interest:
Do you think the race condition happens in the kernel / between zellij and other program?
Because safe Rust should not have any race condition bugs...

**Comment by tlinford** [comment]
> Out of interest:
> Do you think the race condition happens in the kernel / between zellij and other program?
> Because safe Rust should not have any race condition bugs...

My understanding is a bit limited of the full flow of opening ptys etc - but as far as I can tell the heart of the issue here is that we are passing around and using `RawFd`, which is effectively just a number, so rust can't really prevent us trying to write to a closed file with this api.

**Comment by raphCode** [comment]
Yep, `Raw*` sounds pretty unsafe to me :D

**Pull request merged**
