### PR TITLE
Adding solarized-light

### PR DESCRIPTION
**Pull request by TornaxO7**
I was missing this file so I'm just adding it :)

### CODE REVIEW

**Comment by a-kenji** [comment]
Thank you @TornaxO7 !

**Comment by TornaxO7** [comment]
image
might be nice to add an image as well: That's how it looks like on my system with the `kitty` terminal

**Comment by a-kenji** [comment]
We automatically generate the themes into the documentation periodically. 
https://zellij.dev/documentation/theme-gallery.html

You could run a pr against the documenation website, if you want!

**Comment by TornaxO7** [comment]
Oooooh ok, that's neat! Then I won't upload my one :)

**Pull request merged**
