### PR TITLE
add tab toolbar

### PR DESCRIPTION
**Pull request by jcaplan**
#166 

This is adds a toolbar showing the current tab. Tabs are only identified by number. You can select the tab by number key in addition to j and k key bindings.

### CODE REVIEW

**Comment by categorille** [comment]
seems cool and good to me :)

**Comment by categorille** [comment]
great work! i found two issues tho

1) i got a crash at some point but wasn't able to reproduce it. It involved deleting and moving to tabs in a certain order. I'll try to reproduce it

2) if you create a total of 3 tabs, then delete the one in the middle, then the asterisk doesn't replace the dash when the first tab is selected. This seems to happen whenever a tab is deleted in the middle or at the left of the tab list.

**Comment by categorille** [comment]
I was able to reproduce the crash by having 3 tabs open, with the first one selected, and pressing 3 and x almost simultaneously (don't know what one was first). Here's the call trace:

```
Error: thread 'screen' panicked at 'called `Option::unwrap()` on a `None` value': src/common/screen.rs:146
   0: zellij::common::errors::handle_panic
             at src/common/errors.rs:26:21
   1: zellij::common::start::{{closure}}
             at src/common/mod.rs:207:13
   2: std::panicking::rust_panic_with_hook
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:597:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:497:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   6: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   7: core::panicking::panic
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50:5
   8: core::option::Option<T>::unwrap
             at /home/adel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:386:21
   9: zellij::common::screen::Screen::switch_tab_prev
             at src/common/screen.rs:146:29
  10: zellij::common::screen::Screen::close_tab
             at src/common/screen.rs:178:13
  11: zellij::common::start::{{closure}}
             at src/common/mod.rs:414:56
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /home/adel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  13: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /home/adel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:474:17
  14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/adel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:322:9
  15: std::panicking::try::do_call
             at /home/adel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:381:40
  16: __rust_try
  17: std::panicking::try
             at /home/adel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:345:19
  18: std::panic::catch_unwind
             at /home/adel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:396:14
  19: std::thread::Builder::spawn_unchecked::{{closure}}
             at /home/adel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:473:30
  20: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /home/adel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  21: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/unix/thread.rs:71:17
  22: start_thread
  23: clone
```

**Comment by jcaplan** [comment]
@categorille thanks good catch. should be resolved now.

**Comment by denismaxim0v** [comment]
This looks good, the issue above seems to be fixed. Played around a bit with didn't manage to crash it. What are you plans here @jcaplan, maybe some styling next?

**Comment by jcaplan** [comment]
@denismaxim0v added some color to match the status bar, I think that's as far as I'll take it at this stage. The next thing I was thinking about was being able to name the tabs, but I think that needs a pretty big change to the plugin API because of how  I'm passing in the number of tabs and active index to the web assembly doesn't really generalize. I'm not sure how to pass strings as arguments across the web assembly interface, if there's a way to pass serialized data directly when calling the web assembly handle or if there needs to be a second message pass back from the plugin to query the screen (similar to get_help), and if this will cause deadlock if the screen thread is stuck in render while the plugin is trying to send it a message to complete its pane render... seems like it's own separate issue to solve first.

**Review by denismaxim0v — CHANGES_REQUESTED** [review]
Ok I think it's pretty much ready to be merged. I think we can add things like styling and naming later on, maybe you can take on the naming task? If you need any help you can ask here on github or in discord. The only thing left is, can you @jcaplan please merge the upstream and resolve conflicts before I merge it?

**Review by denismaxim0v — APPROVED** [review]

**Pull request merged**
