### PR TITLE
feat: provide the zellij version to plugins

### LINKED ISSUE #888: Feature: give plugins version information on load
But in this case, the most important thing that how to get the zellij version in plugin.

The thought in my head, when wasmer invoke the function of `load`, pass the version information to plugin. however, it is occured all plugins to receive unnecessary data.

_Originally posted by @jaeheonji in https://github.com/zellij-org/zellij/issues/848#issuecomment-976309075_

### PR DESCRIPTION
**Pull request by jaeheonji**
resolves #888

### CODE REVIEW

**Comment by jaeheonji** [comment]
I did some research on this feature.
The initial (**my stupid**) idea was to provide the zellij version when wasmer invokes the plugin's load function.

For some reason I changed the implementation direction.

1. The data type that can be provided as a plugin through wasmer's call is only integer. Of course other types are possible with "slightly" complicated methods.
2. Already in the `wasm_vm.rs` there is a nice way called `plugin API` !!

So I made a pluginAPI that simply outputs the zellij version. The plugin only needs to call the `get_zellij_version` function.

**Review by a-kenji — APPROVED** [review]
LGTM, but would like to have a 2nd pair of eyes here.

**Comment by TheLostLambda** [comment]
I think we could improve the code here a little, let me experiment for a moment!

**Comment by TheLostLambda** [comment]
Sorry for the delay in getting back to you!

I think we can reuse the `object_from_stdin()` function we already have, since `String` is deserializable!

Here is the diff that worked for me!

image

**Comment by TheLostLambda** [comment]
Otherwise things look stellar! Thanks for doing this @jaeheonji !

**Comment by jaeheonji** [comment]
@TheLostLambda Thanks for reviewing! I applied the part you suggested :)

**Review by a-kenji — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
