### PR TITLE
Fix double panic lockup in clients panic handler

### PR DESCRIPTION
**Pull request by raphCode**
https://github.com/zellij-org/zellij/issues/1326
https://github.com/zellij-org/zellij/issues/1414

### CODE REVIEW

**Comment by raphCode** [comment]
@jaeheonji in case you want to have a look, I solved the problem by returning a `Result` from `unset_raw_mode()`, which must be handled at callsites. I unwrapped it everywhere except in the panic handler.
I also log every panic to the logfile now, since we now know we can't rely on printing to the terminal.

**Review by jaeheonji — APPROVED** [review]
LGMT. This can prevent `panic` from falling into a loop.
Of course, perhaps, the output for errors in `unset_raw_mode` can be unkind, but this would be a very rare case. And I don't think it's a big deal.

**Comment by raphCode** [comment]
> perhaps, the output for errors in `unset_raw_mode` can be unkind

What do you mean? Ugly to handle for the programmer?

**Comment by jaeheonji** [comment]
> > perhaps, the output for errors in `unset_raw_mode` can be unkind
> 
> What do you mean? Ugly to handle for the programmer?

Almost the same, maybe compared to the `handle_panic`, I thought there would be some lack of information, and no pretty output. However, as I have already mentioned, I do not think it is such a big problem. What do you think?

**Comment by jaeheonji** [comment]
Cool! I agree :)

**Pull request merged**
