### PR TITLE
add name section in readme

### PR DESCRIPTION
**Pull request by djalal**
added missing section to clarify the origin of the project name.

### CODE REVIEW

**Comment by IliasHad** [comment]
+1

**Comment by giyany** [comment]
Thank you for the PR!
Explaining the project name makes a lot of sense and telling more people about this beautiful, intricate art form is a huge bonus.

As a footnote, we're aware that there's been some political controversy about the origin and development of this art. Personally, my cultural background is distant enough so that I'm unable to have informed opinions on this topic. So while approving the PR is technically straightforward and fast, it may need some consideration of the best way to meet the code of conduct.

**Comment by imsnif** [comment]
Hi, first - thanks for bringing attention to this issue. For the record, ever since we adopted the name the first word in the README linked to the wikipedia page for Zellij (and still does). But I am happy to make this more explicit and add the section you suggested.

In that venue, how about we use the first paragraph from wikipedia as the text:

## Origin of the Name

*[From Wikipedia, the free encyclopedia](https://en.wikipedia.org/wiki/Zellij)*

Zellij (Arabic: الزليج, romanized: zillīj; also spelled zillij or zellige) is a style of mosaic tilework made from individually hand-chiseled tile pieces. The pieces were typically of different colours and fitted together to form various patterns on the basis of tessellations, most notably elaborate Islamic geometric motifs such as radiating star patterns composed of various polygons. This form of Islamic art is one of the main characteristics of architecture in the western Islamic world. It is found in the architecture of Morocco, the architecture of Algeria, early Islamic sites in Tunisia, and in the historic monuments of al-Andalus (in the Iberian Peninsula).

What do you think @djalal ?

**Comment by djalal** [comment]
excellent, let's do this @imsnif

**Comment by imsnif** [comment]
Great, thanks @djalal !

**Pull request merged**
