### PR TITLE
Add `#[allow(dead_code)]` attribute to unused variables

### PR DESCRIPTION
**Pull request by ken-matsui**
I would suggest deleting these variables unless you think they will be used.
If you would so, I would be pleased to remove them in this PR.

### CODE REVIEW

**Comment by ken-matsui** [comment]
This PR conflicts with https://github.com/zellij-org/zellij/pull/1087.
I would suggest merging either @orhun's or mine.

**Comment by orhun** [comment]
Ah I totally missed that this PR already exists :/

**Comment by ken-matsui** [comment]
Never mind :)

**Comment by ken-matsui** [comment]
Thanks for your opinion. I close this PR, so any changes should be continued on https://github.com/zellij-org/zellij/pull/1087.

**Pull request closed without merging**
