### PR TITLE
fix(mouse): middle or right clicks creating selection

### LINKED ISSUE #1371: Middle or right click creates weird persistent selections
Clicking right selects the clicked pane and displays a selection starting from the top until the clicked position. The selection persists, it is even possible to create multiple selections in different panes:
image

Clicking with the middle mouse button does a similar thing, except it does not switch the active pane, so you can manipulate the selection in the active pane by middle-clicking in another pane. In the screenshot, middle-clicking in the right pane causes all lines down to the cursor position in the left pane to be selected.

In both cases, this only happens when the mouse button is released.
v0.29.1

### PR DESCRIPTION
**Pull request by tlinford**
fix #1371

### CODE REVIEW

**Comment by tlinford** [comment]
@raphCode would you mind giving this a spin to see if it doesn't cause other problems?

**Comment by raphCode** [comment]
I couldn't find any mouse-related problem in a quick test drive!
Nice :)

**Comment by tlinford** [comment]
> I couldn't find any mouse-related problem in a quick test drive! Nice :)

thanks!

not sure what is wrong with the e2e tests, it's failing on the `Install cargo-make` step with:
`warning: error: unable to download 'https://api.github.com/repos/NixOS/nixpkgs/tarball/b283b64580d1872333a99af2b4cef91bb84580cf': HTTP error 500 ('')`.

**Comment by raphCode** [comment]
> > I couldn't find any mouse-related problem in a quick test drive! Nice :)
> 
> thanks!
> 
> not sure what is wrong with the e2e tests, it's failing on the `Install cargo-make` step with: `warning: error: unable to download 'https://api.github.com/repos/NixOS/nixpkgs/tarball/b283b64580d1872333a99af2b4cef91bb84580cf': HTTP error 500 ('')`.

I also just noticed similar problems on a different PR, so it seems the CI has a hiccup atm.

**Pull request merged**
