### PR TITLE
Refactor match session name

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Found this while browsing the source.

### CODE REVIEW

**Review by a-kenji — APPROVED** [review]
LGTM, thank you!

Do you want to squash it?

**Comment by matthiasbeyer** [comment]
Yes, gonna do it tomorrow though. Hope that's ok.

**Comment by a-kenji** [comment]
Sure, no rush!

**Comment by matthiasbeyer** [comment]
Here we go :tada:

**Comment by a-kenji** [comment]
Thank you!

**Comment by matthiasbeyer** [comment]
You're very welcome! :laughing:

**Pull request merged**
