### PR TITLE
Add new dependencies to `CONTRIBUTING.md`

### PR DESCRIPTION
**Pull request by a-kenji**
I hit this while trying to test the new system, 
are these dependencies correct?

### CODE REVIEW

**Comment by imsnif** [comment]
The new test system is just about running `e2e-test`... did it change the normal test for you too? (I personally haven't encountered a need for these packages in either `test` or `e2e-test`, but that doesn't mean it's not true to other systems)

**Comment by a-kenji** [comment]
They seem to have been needed by `openssl-sys`.
It seems to need it even for the `cargo make test` case.

`ssh2` -> `libssh2-sys` -> `openssl-sys` -> `openssl` & `pkg-config`.

Maybe you have already openssl and pkg-config installed?

**Comment by imsnif** [comment]
Ah yeah - ok. That's the `ssh2` package that we use in order to connect to the docker container in the e2e tests. It's a dependency of our tests, which is why you're getting this I suppose.
Good find, thanks!

**Comment by a-kenji** [comment]
Ok, then I will merge this, thanks for the sanity check!

**Pull request merged**
